[build]
  base = "/"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18" # Specify the Node.js version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200