[build]
  base = "/"
  publish = "build"
  command = "npm install --no-optional --ignore-scripts && npm run build"

[build.environment]
  NODE_VERSION = "16" # Specify the Node.js version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200